version: "3"

services:
  server-eleven-test:
    image: node:20-alpine
    volumes:
      - ./:/code/
    working_dir: /code/
    ports:
      - "4000:4000"
    networks:
      - dbnet
    command: npm run dev
  db-eleven-test:
    image: mysql:8.2.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: eleven11
      MYSQL_USER: eleven
      MYSQL_PASSWORD: eleven11
      MYSQL_DATABASE: eleven
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - dbnet

volumes:
  mysql:

networks:
  dbnet:
